[package]
name = "trading-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.37"
ordered-float = "4.2.0"
rust_decimal = "1.35.0"
rust_decimal_macros = "1.34.2"
